version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      db:
        condition: service_healthy
    build: .
    container_name: node_app
    env_file: ./.env
    environment:
      - PORT=${PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
